language: python

python:
  - "3.6"

    # command to install dependencies
install:
    - pip install .[test]
    - pip install coveralls

# command to run tests
script:
    - tox

after_success:
  - coverage report
  - coveralls
